spring:
  application:
    name: catalog
  profiles:
    active: dev
  jpa:
    open-in-view: false # Transactions are closed before view rendering

cors:
  origins:${CORS_ORIGINS:http://localhost:5173,http://localhost:3000}

# mysql
#spring.datasource.url=jdbc:mysql://localhost:3306/seu_banco
#spring.datasource.username=root
#spring.datasource.password=root
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true